'use client';

import React, { useState, useEffect } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { PositionService } from '@/lib/services/positionService';
import { SubsystemService } from '@/lib/services/subsystemService';
import { ProjectService } from '@/lib/services/projectService';
import { Position, Teilsystem, Projekt } from '@/types';
import { ArrowLeft, UploadCloud, FileType } from 'lucide-react';
import Link from 'next/link';
import { cn } from '@/lib/utils';

const positionSchema = z.object({
    name: z.string().min(3, 'Bezeichnung muss mindestens 3 Zeichen lang sein'),
    menge: z.coerce.number().min(1, 'Menge muss mindestens 1 sein'),
    einheit: z.string().min(1, 'Einheit ist erforderlich'),
    teilsystemId: z.string().min(1, 'Teilsystem ist erforderlich'),
    status: z.string().min(1, 'Status ist erforderlich'),
});

type PositionValues = z.infer<typeof positionSchema>;

export default function PositionErfassenPage() {
    const { projektId } = useParams() as { projektId: string };
    const searchParams = useSearchParams();
    const router = useRouter();
    const teilsystemId = searchParams.get('teilsystemId');
    const [dragActive, setDragActive] = useState(false);
    const fileInputRef = React.useRef<HTMLInputElement>(null);
    const [teilsystem, setTeilsystem] = useState<Teilsystem | null>(null);
    const [project, setProject] = useState<Projekt | null>(null);

    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files && e.target.files[0]) {
            console.log("File selected:", e.target.files[0].name);
            alert(`Datei "${e.target.files[0].name}" zum Upload bereit.`);
        }
    };

    const {
        register,
        handleSubmit,
        formState: { errors, isSubmitting },
    } = useForm<PositionValues>({
        resolver: zodResolver(positionSchema),
        defaultValues: {
            status: 'offen',
            einheit: 'Stk',
            teilsystemId: teilsystemId || '',
        }
    });

    useEffect(() => {
        const loadContext = async () => {
            if (teilsystemId) {
                const ts = await SubsystemService.getTeilsystemById(teilsystemId);
                setTeilsystem(ts);
            }
            if (projektId) {
                const p = await ProjectService.getProjektById(projektId);
                setProject(p);
            }
        };
        loadContext();
    }, [teilsystemId, projektId]);

    const onSubmit = async (data: PositionValues) => {
        try {
            const newItem: Partial<Position> = {
                // ID generated by service
                ...data,
                teilsystemId: teilsystemId || data.teilsystemId,
                status: data.status as any
            };

            await PositionService.createPosition(newItem);
            router.push(`/${projektId}/teilsysteme/${teilsystemId}`);
        } catch (error) {
            console.error("Failed to create position", error);
            alert("Fehler beim Speichern");
        }
    };

    const handleDrag = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        if (e.type === "dragenter" || e.type === "dragover") {
            setDragActive(true);
        } else if (e.type === "dragleave") {
            setDragActive(false);
        }
    };

    const handleDrop = (e: React.DragEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setDragActive(false);
        if (e.dataTransfer.files && e.dataTransfer.files[0]) {
            // Handle file upload logic here
            console.log("File dropped:", e.dataTransfer.files[0].name);
            alert(`Datei "${e.dataTransfer.files[0].name}" zum Upload bereit.`);
        }
    };

    if (!teilsystemId) {
        return <div className="p-10 text-center text-red-500 font-bold">Fehler: Keine Teilsystem-ID angegeben.</div>;
    }

    return (
        <div className="space-y-6 animate-in fade-in duration-500 pb-12">
            {/* Back Button */}
            <div className="flex justify-end mb-4">
                <Link href={`/${projektId}/teilsysteme/${teilsystemId}`}>
                    <Button variant="outline" size="sm" className="bg-muted hover:bg-muted/80 text-foreground font-bold h-9 text-xs">
                        <ArrowLeft className="h-3 w-3 mr-1" />
                        Zurück zum Teilsystem
                    </Button>
                </Link>
            </div>

            {/* Header Card similar to Detail Page */}
            <div className="bg-card p-6 rounded-2xl shadow-sm border border-border flex justify-between items-center">
                <div className="space-y-1">
                    <span className="text-[10px] font-black text-primary uppercase tracking-[0.2em]">NEUE POSITION ZUORDNEN</span>
                    <div className="flex items-baseline gap-2">
                        <span className="text-3xl font-black text-foreground tracking-tight">TS {(teilsystem?.teilsystemNummer || teilsystemId || '').replace(/^ts\s?/i, '')}</span>
                        <span className="text-3xl font-black text-foreground tracking-tight">{teilsystem?.name}</span>
                    </div>
                </div>
            </div>

            <form onSubmit={handleSubmit(onSubmit)} className="space-y-8">
                <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
                    {/* Left Column: Information */}
                    <div className="lg:col-span-3 h-full flex flex-col">
                        <Card className="shadow-sm border-none flex-1">
                            <CardHeader className="py-3 px-4 bg-muted/30 border-b">
                                <CardTitle className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-2">
                                    <FileType className="h-3.5 w-3.5" />
                                    Positions Details
                                </CardTitle>
                            </CardHeader>
                            <CardContent className="space-y-6 p-6">
                                <input type="hidden" {...register('teilsystemId')} />

                                <div className="space-y-6">
                                    <Input label="Bezeichnung" placeholder="z.B. Fensterfront Typ A" {...register('name')} error={errors.name?.message} />
                                    <div className="grid grid-cols-2 gap-6">
                                        <Input label="Menge" type="number" {...register('menge')} error={errors.menge?.message} />
                                        <Input label="Einheit" placeholder="Stk, m, m2" {...register('einheit')} error={errors.einheit?.message} />
                                    </div>
                                    <Select label="Status" options={[{ label: 'Offen', value: 'offen' }, { label: 'Bestellt', value: 'bestellt' }]} {...register('status')} error={errors.status?.message} />
                                </div>
                            </CardContent>
                        </Card>
                    </div>

                    {/* Right Column: File Upload - Compact size & Sticky */}
                    <div className="space-y-6 sticky top-6 mt-1 lg:mt-[4.5rem]">
                        <Card className="shadow-none border-2 border-dashed border-border bg-muted/30 flex flex-col">
                            <CardHeader className="bg-transparent border-b-0 pb-0 pt-4 px-4">
                                <CardTitle className="text-sm font-black text-foreground flex items-center gap-2">
                                    <UploadCloud className="h-4 w-4 text-primary" />
                                    Dateien hochladen
                                </CardTitle>
                            </CardHeader>
                            <CardContent
                                className={cn(
                                    "flex flex-col items-center justify-center p-4 transition-colors cursor-pointer m-2 rounded-lg border-2 border-transparent hover:bg-muted/50",
                                    dragActive ? "bg-primary/5 border-primary border-dashed" : ""
                                )}
                                onDragEnter={handleDrag}
                                onDragLeave={handleDrag}
                                onDragOver={handleDrag}
                                onDrop={handleDrop}
                                onClick={() => fileInputRef.current?.click()}
                            >
                                <div className="bg-background p-3 rounded-full shadow-sm mb-3">
                                    <FileType className="h-6 w-6 text-primary" />
                                </div>
                                <h3 className="text-xs font-bold text-foreground mb-1">Dateien hierher ziehen</h3>
                                <p className="text-[10px] font-medium text-muted-foreground mb-4 text-center">
                                    PDF, DXF, DWG, images (Max. 50MB)
                                </p>
                                <Button type="button" size="sm" variant="outline" className="text-xs font-bold border-border h-8 px-4" onClick={(e) => { e.stopPropagation(); fileInputRef.current?.click(); }}>
                                    Wählen
                                </Button>
                                <input
                                    type="file"
                                    className="hidden"
                                    ref={fileInputRef}
                                    onChange={handleFileSelect}
                                />
                            </CardContent>
                        </Card>
                    </div>
                </div>

                <div className="flex justify-end pt-4 border-t border-border">
                    <Button type="submit" size="lg" className="font-black px-12 h-12 text-base shadow-xl shadow-primary/20 hover:scale-105 transition-transform" disabled={isSubmitting}>
                        {isSubmitting ? 'Wird gespeichert...' : 'Position speichern'}
                    </Button>
                </div>
            </form>
        </div>
    );
}
