'use client';

import React from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Select } from '@/components/ui/select';
import { Button } from '@/components/ui/button';
import { EmployeeService } from '@/lib/services/employeeService';
import { Mitarbeiter } from '@/types';
import { ArrowLeft, Plus } from 'lucide-react';
import Link from 'next/link';

const mitarbeiterSchema = z.object({
    vorname: z.string().min(2, 'Vorname ist erforderlich'),
    nachname: z.string().min(2, 'Nachname ist erforderlich'),
    email: z.string().email('Ungültige E-Mail-Adresse'),
    department: z.string().optional(),
    rolle: z.string().min(1, 'Rolle ist erforderlich'),
});

type MitarbeiterValues = z.infer<typeof mitarbeiterSchema>;

export default function MitarbeiterErfassenPage() {
    const { projektId } = useParams() as { projektId: string };
    const router = useRouter();

    const {
        register,
        handleSubmit,
        formState: { errors, isSubmitting },
    } = useForm<MitarbeiterValues>({
        resolver: zodResolver(mitarbeiterSchema),
        defaultValues: {
            rolle: 'mitarbeiter',
        }
    });

    const onSubmit = async (data: MitarbeiterValues) => {
        try {
            const newItem: Partial<Mitarbeiter> = {
                // ID generated by service
                ...data,
                department: data.department,
                role: data.rolle as any
            };

            await EmployeeService.createMitarbeiter(newItem);
            router.push(`/${projektId}/mitarbeiter`);
        } catch (error) {
            console.error("Failed to create employee", error);
            alert("Fehler beim Speichern");
        }
    };

    const rolleOptions = [
        { label: 'Bitte wählen...', value: '' },
        { label: 'Admin', value: 'admin' },
        { label: 'Projektleiter', value: 'projektleiter' },
        { label: 'Mitarbeiter', value: 'mitarbeiter' },
    ];

    const departmentOptions = [
        { label: 'Bitte wählen...', value: '' },
        { label: 'Projektleitung', value: 'Projektleitung' },
        { label: 'Planung', value: 'Planung' },
        { label: 'Produktion', value: 'Produktion' },
        { label: 'Montage', value: 'Montage' },
        { label: 'Administration', value: 'Administration' },
    ];

    return (
        <div className="max-w-3xl mx-auto space-y-6">
            <Link href={`/${projektId}/mitarbeiter`} className="inline-flex items-center text-sm font-bold text-slate-500 hover:text-primary transition-colors">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Zurück zur Liste
            </Link>
            <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Mitarbeiter hinzufügen</h1>
            <form onSubmit={handleSubmit(onSubmit)}>
                <Card className="shadow-xl">
                    <CardHeader><CardTitle>Mitarbeiter Details</CardTitle></CardHeader>
                    <CardContent className="space-y-6">
                        <div className="grid grid-cols-2 gap-4">
                            <Input label="Vorname" placeholder="Erika" {...register('vorname')} error={errors.vorname?.message} />
                            <Input label="Nachname" placeholder="Mustermann" {...register('nachname')} error={errors.nachname?.message} />
                        </div>
                        <Input label="E-Mail" type="email" placeholder="e.mustermann@methabau.ch" {...register('email')} error={errors.email?.message} />
                        <div className="grid grid-cols-2 gap-4">
                            <Select label="Abteilung" options={departmentOptions} {...register('department')} error={(errors as any).department?.message} />
                            <Select label="Rolle" options={rolleOptions} {...register('rolle')} error={errors.rolle?.message} />
                        </div>

                        <div className="space-y-2">
                            <label className="text-sm font-semibold text-slate-700 ml-1">Profilbild</label>
                            <div className="flex items-center gap-6 p-4 border-2 border-dashed border-slate-200 rounded-2xl hover:border-primary hover:bg-orange-50/30 transition-all cursor-pointer group">
                                <div className="h-16 w-16 rounded-full bg-slate-100 flex items-center justify-center border-2 border-white shadow-sm overflow-hidden text-slate-400 group-hover:text-primary transition-colors">
                                    <div className="flex flex-col items-center">
                                        <Plus className="h-6 w-6" />
                                    </div>
                                </div>
                                <div>
                                    <p className="text-sm font-bold text-slate-700">Bild hochladen</p>
                                    <p className="text-xs text-slate-400 font-medium mt-0.5">JPG o PNG, max. 2MB</p>
                                </div>
                            </div>
                        </div>
                    </CardContent>
                    <CardFooter className="bg-slate-50 border-t p-6 flex justify-end gap-4">
                        <Button type="submit" className="font-bold min-w-[140px]" disabled={isSubmitting}>
                            {isSubmitting ? 'Wird gespeichert...' : 'Hinzufügen'}
                        </Button>
                    </CardFooter>
                </Card>
            </form>
        </div>
    );
}
