'use client';

import React from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { MaterialService } from '@/lib/services/materialService';
import { Material } from '@/types';
import { ArrowLeft, Save } from 'lucide-react';
import Link from 'next/link';

const materialSchema = z.object({
    name: z.string().min(3, 'Bezeichnung muss mindestens 3 Zeichen lang sein'),
    hersteller: z.string().min(2, 'Hersteller ist erforderlich'),
    artikelnummer: z.string().min(1, 'Artikelnummer ist erforderlich'),
    status: z.string().min(1, 'Status ist erforderlich'),
});

type MaterialValues = z.infer<typeof materialSchema>;

export default function MaterialErfassenPage() {
    const { projektId } = useParams() as { projektId: string };
    const router = useRouter();

    const {
        register,
        handleSubmit,
        formState: { errors, isSubmitting },
    } = useForm<MaterialValues>({
        resolver: zodResolver(materialSchema),
        defaultValues: {
            status: 'offen',
        }
    });

    const onSubmit = async (data: MaterialValues) => {
        try {
            const newItem: Partial<Material> = {
                // ID generated by service
                ...data,
                status: data.status as any
            };

            await MaterialService.createMaterial(newItem);
            router.push(`/${projektId}/material`);
        } catch (error) {
            console.error("Failed to create material", error);
            alert("Fehler beim Speichern");
        }
    };

    return (
        <div className="max-w-3xl mx-auto space-y-6">
            <Link href={`/${projektId}/material`} className="inline-flex items-center text-sm font-bold text-slate-500 hover:text-primary transition-colors">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Zurück zur Liste
            </Link>
            <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Material erfassen</h1>
            <form onSubmit={handleSubmit(onSubmit)}>
                <Card className="shadow-xl">
                    <CardHeader><CardTitle>Material Details</CardTitle></CardHeader>
                    <CardContent className="space-y-6">
                        <Input label="Bezeichnung" placeholder="z.B. Alu-Profil 60x120" {...register('name')} error={errors.name?.message} />
                        <Input label="Hersteller" placeholder="z.B. Schüco" {...register('hersteller')} error={errors.hersteller?.message} />
                        <Input label="Artikelnummer" placeholder="z.B. SC-10045" {...register('artikelnummer')} error={errors.artikelnummer?.message} />
                    </CardContent>
                    <CardFooter className="bg-slate-50 border-t p-6 flex justify-end gap-4">
                        <Button type="submit" className="font-bold min-w-[140px]" disabled={isSubmitting}>
                            {isSubmitting ? 'Wird gespeichert...' : 'Speichern'}
                        </Button>
                    </CardFooter>
                </Card>
            </form>
        </div>
    );
}
